doctrine:
  dbal:
    driver: 'pdo_mysql'
    server_version: '8.0'
    charset: UTF8MB4
    url: '%env(resolve:DATABASE_URL)%'

  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Database/Entity'
        prefix: 'App\Infrastructure\Persistence\Database\Entity'
        alias: App
    dql:
      string_functions:
        GROUP_CONCAT: DoctrineExtensions\Query\Mysql\GroupConcat
        IF: DoctrineExtensions\Query\Mysql\IfElse
